[build-system]
requires = ["setuptools>=80.9.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "microsoft-agent"
version = "0.2.12"
description = "Microsoft Graph Agent MCP Server"
readme = "README.md"
authors = [{ name = "Audel Rouhi", email = "knucklessg1@gmail.com" }]
license = { text = "MIT" }
classifiers = [
    "Development Status :: 3 - Alpha",
    "License :: OSI Approved :: MIT License",
    "Environment :: Console",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python :: 3",
]
requires-python = ">=3.10"
dependencies = [
    "requests>=2.32.0",
    "urllib3>=2.2.2",
    "msal>=1.31.0",
    "keyring>=25.1.0",
    "msgraph-sdk>=1.54.0"
]

[project.optional-dependencies]
mcp = [
    "fastmcp>=3.0.0b1",
    "eunomia-mcp>=0.3.10",
    "fastapi>=0.128.0"
]

a2a = [
    "pydantic-ai-slim[fastmcp,openai,anthropic,groq,mistral,google,huggingface,a2a,ag-ui,web]>=1.58.0",
    "pydantic-ai-skills>=v0.4.0",
    "fastapi>=0.128.0"
]

all = [
    "fastmcp>=3.0.0b1",
    "eunomia-mcp>=0.3.10",
    "pydantic-ai-slim[fastmcp,openai,anthropic,groq,mistral,google,huggingface,a2a,ag-ui,web]>=1.58.0",
    "pydantic-ai-skills>=v0.4.0",
    "fastapi>=0.128.0"
]

[project.scripts]
microsoft-mcp = "microsoft_agent.microsoft_mcp:microsoft_mcp"
microsoft-agent = "microsoft_agent.microsoft_agent:agent_server"

[tool.setuptools.packages.find]
where = ["."]

[tool.setuptools]
include-package-data = true

[tool.setuptools.package-data]
microsoft_agent = ["mcp_config.json", "skills/**"]
